Complex Docs: demo::algo::Pipeline< S > Class Template Reference
demo::algo::Pipeline< S > Class Template Reference
可组合的整数处理管线
#include <pipeline.hpp>
Public Member Functions
Pipeline (S... s)
int run (Reader &r)
从 Reader 读取、经过各阶段，构建 AST 并求值
Private Member Functions
template<std::size_t I, std::size_t N = sizeof...(S)>
requires (I >=N) void build_ast(std
template<std::size_t I, std::size_t N = sizeof...(S)>
requires (I< N) void build_ast(std
Static Private Member Functions
static std::string to_string (const Node &n)
Private Attributes
std::tuple< S... > stages_
Detailed Description
template<Stage... S>
class demo::algo::Pipeline< S >
可组合的整数处理管线
Template Parameters
S 可变参数阶段（满足 Stage）
Definition at line 38 of file pipeline.hpp.
Constructor & Destructor Documentation
Pipeline()
template<Stage... S> demo::algo::Pipeline< S >::Pipeline (S... s) inline explicit
Definition at line 40 of file pipeline.hpp.
References demo::algo::Pipeline< S >::stages_.
Referenced by run().
Member Function Documentation
requires() [1/2]
template<Stage... S> template<std::size_t I, std::size_t N = sizeof...(S)> demo::algo::Pipeline< S >::requires (I >= N) inline private
Definition at line 75 of file pipeline.hpp.
requires() [2/2]
template<Stage... S> template<std::size_t I, std::size_t N = sizeof...(S)> demo::algo::Pipeline< S >::requires () inline private
Definition at line 79 of file pipeline.hpp.
References demo::algo::Pipeline< S >::stages_.
run()
template<Stage... S> int demo::algo::Pipeline< S >::run (Reader & r) inline
从 Reader 读取、经过各阶段，构建 AST 并求值
Definition at line 58 of file pipeline.hpp.
References demo::util::Result< T >::error(), demo::core::Logger::error(), demo::core::Node::eval(), demo::util::Result< T >::has_value(), demo::core::Logger::info(), demo::core::Logger::instance(), demo::io::Reader::read_one(), demo::algo::Pipeline< S >::to_string(), and demo::util::Result< T >::value().
Referenced by run().
to_string()
template<Stage... S> static std::string demo::algo::Pipeline< S >::to_string (const Node & n) inline static private
Definition at line 93 of file pipeline.hpp.
Referenced by demo::algo::Pipeline< S >::run().
Member Data Documentation
stages_
template<Stage... S> std::tuple<S...> demo::algo::Pipeline< S >::stages_ private
Definition at line 72 of file pipeline.hpp.
Referenced by demo::algo::Pipeline< S >::Pipeline(), and demo::algo::Pipeline< S >::requires().
The documentation for this class was generated from the following file:
include/algo/pipeline.hpp