Complex Docs: demo::core::Logger Class Reference
demo::core::Logger Class Reference
线程安全的 Logger（PImpl）
#include <logger.hpp>
Classes
struct Impl
Public Member Functions
void set_level (int level)
void info (const std::string &msg) const
void error (const std::string &msg) const
Logger (Logger &&) noexcept
Logger & operator= (Logger &&) noexcept
~Logger ()
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Static Public Member Functions
static Logger & instance ()
单例
Private Member Functions
Logger ()
Private Attributes
std::unique_ptr< Impl > p_
Detailed Description
线程安全的 Logger（PImpl）
Definition at line 16 of file logger.hpp.
Constructor & Destructor Documentation
Logger() [1/3]
demo::core::Logger::Logger (Logger &&) default noexcept
~Logger()
demo::core::Logger::~Logger () default
Logger() [2/3]
demo::core::Logger::Logger (const Logger &) delete
Logger() [3/3]
demo::core::Logger::Logger () private
Definition at line 17 of file logger.cpp.
References p_.
Member Function Documentation
error()
void demo::core::Logger::error (const std::string & msg) const
Definition at line 29 of file logger.cpp.
References demo::core::Logger::Impl::log(), and p_.
Referenced by demo::algo::Pipeline< S >::run().
info()
void demo::core::Logger::info (const std::string & msg) const
Definition at line 28 of file logger.cpp.
References demo::core::Logger::Impl::level, demo::core::Logger::Impl::log(), and p_.
Referenced by run(), and demo::algo::Pipeline< S >::run().
instance()
Logger & demo::core::Logger::instance () static
单例
Definition at line 22 of file logger.cpp.
Referenced by run(), and demo::algo::Pipeline< S >::run().
operator=() [1/2]
Logger& demo::core::Logger::operator= (const Logger &) delete
operator=() [2/2]
Logger & demo::core::Logger::operator= (Logger &&) default noexcept
set_level()
void demo::core::Logger::set_level (int level)
Definition at line 27 of file logger.cpp.
References demo::core::Logger::Impl::level, and p_.
Referenced by run().
Member Data Documentation
p_
std::unique_ptr<Impl> demo::core::Logger::p_ private
Definition at line 34 of file logger.hpp.
Referenced by error(), info(), Logger(), and set_level().
The documentation for this class was generated from the following files:
include/core/logger.hpp
src/logger.cpp