Complex Docs: demo::util::Result< T > Class Template Reference
demo::util::Result< T > Class Template Reference
成功时含值，失败时含错误消息
#include <result.hpp>
Public Member Functions
bool has_value () const noexcept
T & value ()
const std::string & error () const
Static Public Member Functions
static Result ok (T v)
static Result err (std::string e)
Private Member Functions
Result (std::optional< T > v, std::string e)
Private Attributes
std::optional< T > val_
std::string err_
Detailed Description
template<class T>
class demo::util::Result< T >
成功时含值，失败时含错误消息
Definition at line 16 of file result.hpp.
Constructor & Destructor Documentation
Result()
template<class T > demo::util::Result< T >::Result (std::optional< T > v, std::string e) inline private
Definition at line 28 of file result.hpp.
References demo::util::Result< T >::err_, and demo::util::Result< T >::val_.
Member Function Documentation
err()
template<class T > static Result demo::util::Result< T >::err (std::string e) inline static
Definition at line 19 of file result.hpp.
error()
template<class T > const std::string& demo::util::Result< T >::error () const inline
Definition at line 23 of file result.hpp.
References demo::util::Result< T >::err_.
Referenced by demo::algo::Pipeline< S >::run().
has_value()
template<class T > bool demo::util::Result< T >::has_value () const inline noexcept
Definition at line 21 of file result.hpp.
References demo::util::Result< T >::val_.
Referenced by demo::algo::Pipeline< S >::run().
ok()
template<class T > static Result demo::util::Result< T >::ok (T v) inline static
Definition at line 18 of file result.hpp.
value()
template<class T > T& demo::util::Result< T >::value () inline
Definition at line 22 of file result.hpp.
References demo::util::Result< T >::val_.
Referenced by demo::algo::Pipeline< S >::run().
Member Data Documentation
err_
template<class T > std::string demo::util::Result< T >::err_ private
Definition at line 27 of file result.hpp.
Referenced by demo::util::Result< T >::error(), and demo::util::Result< T >::Result().
val_
template<class T > std::optional<T> demo::util::Result< T >::val_ private
Definition at line 26 of file result.hpp.
Referenced by demo::util::Result< T >::has_value(), demo::util::Result< T >::Result(), and demo::util::Result< T >::value().
The documentation for this class was generated from the following file:
include/util/result.hpp