Complex Docs: demo::util::ScopeGuard::Concept Struct Reference
demo::util::ScopeGuard::Concept Struct Reference abstract
Public Member Functions
virtual ~Concept ()=default
virtual void call () noexcept=0
Detailed Description
Definition at line 32 of file scope_guard.hpp.
Constructor & Destructor Documentation
~Concept()
virtual demo::util::ScopeGuard::Concept::~Concept () virtual default
Referenced by call().
Member Function Documentation
call()
virtual void demo::util::ScopeGuard::Concept::call () pure virtual noexcept
Implemented in demo::util::ScopeGuard::Model< F >.
References ~Concept().
Referenced by demo::util::ScopeGuard::~ScopeGuard().
The documentation for this struct was generated from the following file:
include/util/scope_guard.hpp