Complex Docs: demo::core::Node Struct Reference
demo::core::Node Struct Reference abstract
#include <node.hpp>
Public Member Functions
virtual ~Node ()=default
virtual Kind kind () const noexcept=0
virtual int eval () const =0
计算值
virtual void dump (std::ostream &) const =0
Detailed Description
Definition at line 19 of file node.hpp.
Constructor & Destructor Documentation
~Node()
virtual demo::core::Node::~Node () virtual default
Member Function Documentation
dump()
virtual void demo::core::Node::dump (std::ostream &) const pure virtual
Implemented in demo::core::Mul, demo::core::Add, and demo::core::Literal.
Referenced by demo::core::Add::dump(), demo::core::Mul::dump(), and demo::core::operator<<().
eval()
virtual int demo::core::Node::eval () const pure virtual
计算值
Implemented in demo::core::Mul, demo::core::Add, and demo::core::Literal.
Referenced by demo::core::Add::eval(), demo::core::Mul::eval(), and demo::algo::Pipeline< S >::run().
kind()
virtual Kind demo::core::Node::kind () const pure virtual noexcept
Implemented in demo::core::Mul, demo::core::Add, and demo::core::Literal.
The documentation for this struct was generated from the following file:
include/core/node.hpp